package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.GroupTable;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface GroupTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_TABLE
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_TABLE
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    int insert(GroupTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_TABLE
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    GroupTable selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_TABLE
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    List<GroupTable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_TABLE
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    int updateByPrimaryKey(GroupTable record);
}