package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.GroupTable;
import lt.vu.mybatis.model.GroupTableExample;
import org.apache.ibatis.annotations.Param;

public interface GroupTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_TABLE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    long countByExample(GroupTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_TABLE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    int deleteByExample(GroupTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_TABLE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_TABLE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    int insert(GroupTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_TABLE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    int insertSelective(GroupTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_TABLE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    List<GroupTable> selectByExample(GroupTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_TABLE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    GroupTable selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_TABLE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    int updateByExampleSelective(@Param("record") GroupTable record, @Param("example") GroupTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_TABLE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    int updateByExample(@Param("record") GroupTable record, @Param("example") GroupTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_TABLE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    int updateByPrimaryKeySelective(GroupTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUP_TABLE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    int updateByPrimaryKey(GroupTable record);
}