package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Lecture;
import lt.vu.mybatis.model.LectureExample;
import org.apache.ibatis.annotations.Param;

public interface LectureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    long countByExample(LectureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    int deleteByExample(LectureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    int insert(Lecture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    int insertSelective(Lecture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    List<Lecture> selectByExample(LectureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    Lecture selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    int updateByExampleSelective(@Param("record") Lecture record, @Param("example") LectureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    int updateByExample(@Param("record") Lecture record, @Param("example") LectureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    int updateByPrimaryKeySelective(Lecture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    int updateByPrimaryKey(Lecture record);
}