package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Lecture;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface LectureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURE
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURE
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    int insert(Lecture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURE
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    Lecture selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURE
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    List<Lecture> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.LECTURE
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    int updateByPrimaryKey(Lecture record);
    List<Lecture> selectByStudentId(Long studentId);
}