package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.StudentLecture;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface StudentLectureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_LECTURE
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    int insert(StudentLecture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_LECTURE
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    List<StudentLecture> selectAll();
}