package lt.vu.mybatis.model;

public class GroupTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GROUP_TABLE.ID
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GROUP_TABLE.DISCIPLINE
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    private String discipline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GROUP_TABLE.SEMESTER
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    private Integer semester;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GROUP_TABLE.ID
     *
     * @return the value of PUBLIC.GROUP_TABLE.ID
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GROUP_TABLE.ID
     *
     * @param id the value for PUBLIC.GROUP_TABLE.ID
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GROUP_TABLE.DISCIPLINE
     *
     * @return the value of PUBLIC.GROUP_TABLE.DISCIPLINE
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    public String getDiscipline() {
        return discipline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GROUP_TABLE.DISCIPLINE
     *
     * @param discipline the value for PUBLIC.GROUP_TABLE.DISCIPLINE
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    public void setDiscipline(String discipline) {
        this.discipline = discipline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GROUP_TABLE.SEMESTER
     *
     * @return the value of PUBLIC.GROUP_TABLE.SEMESTER
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    public Integer getSemester() {
        return semester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GROUP_TABLE.SEMESTER
     *
     * @param semester the value for PUBLIC.GROUP_TABLE.SEMESTER
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    public void setSemester(Integer semester) {
        this.semester = semester;
    }
}