package lt.vu.mybatis.model;

public class GroupTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GROUP_TABLE.ID
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GROUP_TABLE.DISCIPLINE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    private String disciplineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GROUP_TABLE.SEMESTER
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    private Integer semesterNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GROUP_TABLE.ID
     *
     * @return the value of PUBLIC.GROUP_TABLE.ID
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GROUP_TABLE.ID
     *
     * @param id the value for PUBLIC.GROUP_TABLE.ID
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GROUP_TABLE.DISCIPLINE
     *
     * @return the value of PUBLIC.GROUP_TABLE.DISCIPLINE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    public String getDisciplineName() {
        return disciplineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GROUP_TABLE.DISCIPLINE
     *
     * @param disciplineName the value for PUBLIC.GROUP_TABLE.DISCIPLINE
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    public void setDisciplineName(String disciplineName) {
        this.disciplineName = disciplineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GROUP_TABLE.SEMESTER
     *
     * @return the value of PUBLIC.GROUP_TABLE.SEMESTER
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    public Integer getSemesterNumber() {
        return semesterNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GROUP_TABLE.SEMESTER
     *
     * @param semesterNumber the value for PUBLIC.GROUP_TABLE.SEMESTER
     *
     * @mbg.generated Sun Mar 30 13:41:02 EEST 2025
     */
    public void setSemesterNumber(Integer semesterNumber) {
        this.semesterNumber = semesterNumber;
    }
}