package lt.vu.mybatis.model;

public class Lecture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LECTURE.ID
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LECTURE.LECTURER
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    private String lecturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.LECTURE.NAME
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LECTURE.ID
     *
     * @return the value of PUBLIC.LECTURE.ID
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LECTURE.ID
     *
     * @param id the value for PUBLIC.LECTURE.ID
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LECTURE.LECTURER
     *
     * @return the value of PUBLIC.LECTURE.LECTURER
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    public String getLecturer() {
        return lecturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LECTURE.LECTURER
     *
     * @param lecturer the value for PUBLIC.LECTURE.LECTURER
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    public void setLecturer(String lecturer) {
        this.lecturer = lecturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.LECTURE.NAME
     *
     * @return the value of PUBLIC.LECTURE.NAME
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.LECTURE.NAME
     *
     * @param name the value for PUBLIC.LECTURE.NAME
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    public void setName(String name) {
        this.name = name;
    }
}