package lt.vu.mybatis.model;

public class StudentLecture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_LECTURE.STUDENT_ID
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_LECTURE.LECTURE_ID
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    private Long lectureId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_LECTURE.STUDENT_ID
     *
     * @return the value of PUBLIC.STUDENT_LECTURE.STUDENT_ID
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_LECTURE.STUDENT_ID
     *
     * @param studentId the value for PUBLIC.STUDENT_LECTURE.STUDENT_ID
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_LECTURE.LECTURE_ID
     *
     * @return the value of PUBLIC.STUDENT_LECTURE.LECTURE_ID
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    public Long getLectureId() {
        return lectureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_LECTURE.LECTURE_ID
     *
     * @param lectureId the value for PUBLIC.STUDENT_LECTURE.LECTURE_ID
     *
     * @mbg.generated Mon Mar 31 12:06:12 EEST 2025
     */
    public void setLectureId(Long lectureId) {
        this.lectureId = lectureId;
    }
}